name       : haskell-old-time
version    : 1.1.0.3
release    : 1
source     :
    - http://hackage.haskell.org/package/old-time-1.1.0.3/old-time-1.1.0.3.tar.gz : 1ccb158b0f7851715d36b757c523b026ca1541e2030d02239802ba39b4112bc1
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides the old time library.
description: |
    This package provides the old time library.
builddeps  :
    - haskell-cabal-install
    - haskell-old-locale
setup      : |
    sed -i "s|4.9|4.10|" old-time.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register

